[model]
# The likelihood terms (implicitly normal distributions):
mist.2MASS_H = [7.400, 0.034]
mist.2MASS_J = [7.702, 0.030]
mist.2MASS_Ks = [7.316, 0.020]
mist.WISE_W1 = [7.203, 0.029]
mist.WISE_W2 = [7.322, 0.020]
mist.WISE_W3 = [7.297, 0.018]
mist.WISE_W4 = ["normal", "c.wise_w4_mean", 0.0114]

# Fix the extinction parameter to 0:
override.mist.Av = "0.0"
# Ignore the distinction between surface and inital bulk [Fe/H]
override.mist.feh = "p.feh0"

# The priors for the remaining parameters:
prior.logAge = ["uniform", -0.5, 1]
prior.logMass0 = ["uniform", -0.5, 0.5]
prior.feh0 = ["uniform", -0.2, 0.5]
prior.parallax = [15.0153, 0.03612]

# Outputs to calculate
outputs = ["d.mistTracks.logRadius", "d.mistTracks.logG", "d.mistTracks.logL"]

[sampling]
sampler = "emcee"
emcee_init.nwalkers = 32
emcee_run.nsteps = 4000

# Example of using a runtime constant (can be changed without recompiling)
const.wise_w4_mean = 7.196

[output]
terminal = true
file = "hd80606.npz"
